# classification

In [2]:
import pandas as pd

In [3]:
# sample classification data

In [7]:
data = {
    "Hours_Studied" :[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Passed" :[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
}

In [8]:
data

{'Hours_Studied': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'Passed': [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]}

In [9]:
df = pd.DataFrame(data)

In [10]:
df

   Hours_Studied  Passed
0              1       0
1              2       0
2              3       0
3              4       0
4              5       0
5              6       1
6              7       1
7              8       1
8              9       1
9             10       1

In [11]:
# Seperate input and output

In [12]:
X = df[["Hours_Studied"]]   
y = df["Passed"]

In [17]:
print(X)

   Hours_Studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

In [18]:
print(y)

0    0
1    0
2    0
3    0
4    0
5    1
6    1
7    1
8    1
9    1
Name: Passed, dtype: int64

In [19]:
# Split data into training and testing

In [29]:
import sklearn

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state=42)

In [25]:
print(X_train)

   Hours_Studied
5              6
0              1
7              8
2              3
9             10
4              5
3              4
6              7

In [26]:
print(X_test)

   Hours_Studied
8              9
1              2

In [27]:
print(y_train)

5    1
0    0
7    1
2    0
9    1
4    0
3    0
6    1
Name: Passed, dtype: int64

In [28]:
print(y_test)

8    1
1    0
Name: Passed, dtype: int64

In [30]:
# Import Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
# Create and Train model

In [34]:
model = LogisticRegression()

In [35]:
model.fit(X_train, y_train)

LogisticRegression()

In [36]:
# Make Predictions

In [37]:
y_pred = model.predict(X_test)

In [40]:
y_pred

array([1, 0])

In [41]:
y_test

8    1
1    0
Name: Passed, dtype: int64

In [46]:
X_test

   Hours_Studied
8              9
1              2

In [53]:
from sklearn.metrics import mean_squared_error

In [54]:
mean_squared_error(y_test, y_pred)

0.0

In [55]:
# predict for new value

In [59]:
new_hours = pd.DataFrame({"Hours_Studied":[7.5]})

In [60]:
new_hours

   Hours_Studied
0            7.5

In [61]:
predicted_marks = model.predict(new_hours)

In [62]:
predicted_marks

array([1])

In [66]:
# calculate the Accuracy Score

In [68]:
from sklearn.metrics import accuracy_score

In [69]:
accuracy_score(y_test, y_pred)

1.0

In [70]:
y_test

8    1
1    0
Name: Passed, dtype: int64

In [71]:
y_prob = model.predict_proba(X_test)

In [73]:
y_prob

array([[0.01799637, 0.98200363],
       [0.98200563, 0.01799437]])